#!/bin/bash
domain=$(cat /etc/xray/domain)
TIMES="10"
CHATID="903400272"
KEY="6228119713:AAEbcPGhjiL1sBhubGcDhFf0EKh6L6wFeYE"
URL="https://api.telegram.org/bot$KEY/sendMessage"
ISP=$(cat /etc/lokasi/isp)
CITY=$(cat /etc/lokasi/city)
domain=$(cat /etc/xray/domain) 
MYIP=$(curl -sS ipv4.icanhazip.com)
IZIN=$(curl -sS https://raw.githubusercontent.com/Anang11042000/Izin/main/Ip | awk '{print 3}' | grep $MYIP)
Name=$(curl -sS https://raw.githubusercontent.com/Anang11042000/Izin/main/Ip | grep $MYIP | awk '{print $2}')

TEXT="
<code>◇━━━━━━━━━━━━━━◇</code>
<b>  ⚠️ AUTOSCRIPT INSTALLER ⚠️</b>
<code>◇━━━━━━━━━━━━━━◇</code>
<b>DOMAIN    :</b> <code>${domain} </code>
<b>IP        :</b> <code>${MYIP} </code>
<b>ISP & CITY:</b> <code>$ISP $CITY </code>
<b>AUTHOR    :</b> <code>$Name </code>
<b>EXP SCRIPT:</b> <code>$IZIN </code>
<code>◇━━━━━━━━━━━━━━◇</code>
"
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
